def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]
pipeline {
    agent any

    tools {
        maven "MAVEN3"
        jdk "OracleJDK11"
    }   

    environment {
        cluster = "vprofile-prod-project"
        service = "vprofile-prod-project"
    }

    stages {
        stage('ECS staging Deploy') {
            steps {
                withAWS(credentials: 'awscreds', region: 'ap-south-1') {
                   sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
    post {
    always {
            echo 'Slack Notifications.'
            slackSend channel: '#ci-jenkins-devops',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}
